/* system 계정에서 실행한다. 	*/
/* Oracle 12c 이상의 버전에서는 사용자 이름 앞에 c##을 붙이도록 되어 있는데 */
/* 아래와 같이 설정하면 임의의 사용자 이름을 사용할 수 있다. */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
DROP USER CNU_RENTCAR CASCADE;
CREATE USER CNU_RENTCAR IDENTIFIED BY 0000 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO CNU_RENTCAR;
GRANT CREATE VIEW, CREATE SYNONYM TO CNU_RENTCAR;
GRANT UNLIMITED TABLESPACE TO CNU_RENTCAR;
ALTER USER CNU_RENTCAR ACCOUNT UNLOCK;